---
- hosts: localhost
  gather_facts: false

  vars:
    sites:
      - ip: '{{ var_host }}'
        token: '{{ var_token }}'
        validate_certs: false
 
  tasks:
    - name: update-truenas-api
      include_tasks: task.yml
      loop: '{{ sites }}'
