---
- name: Checks if there is an update available from update server.
  ansible.builtin.uri::
    method: POST
    url: https://{{ item.ip }}:444/api/v2.0/update/check_available
    return_content: true
    validate_certs: '{{ item.validate_certs }}'
    headers:
      Content-Type: application/json
      Authorization: 'Bearer {{ item.token }}'
  register: truenas_pending_updates

- name: Downloads (if not already in cache) and apply an update.
  ansible.builtin.uri::
    method: POST
    url: https://{{ item.ip }}/api/v2.0/update/update
    return_content: true
    validate_certs: '{{ item.validate_certs }}'
    headers:
      Content-Type: application/json
      Authorization: 'Bearer {{ item.token }}'
  when: "truenas_pending_updates.json.status == 'AVAILABLE'"
